spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/session
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update